sequenceDiagram
    Browser->>Server: POST /login
    Server->>Browser: Set-Cookie: SESSION="user=1234&sig=📝"

    Browser->>Server: GET /home, Cookie: SESSION="user=1234&sig=📝"
    Server->>Browser: Homepage for user 1234
            
